spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/atguigu?userUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    
eureka:
  client:
    register-with-eureka: true #表示是否将自己注册进eurekaserver
    fetch-registry: true #是否从eurekaserver中抓取已有的注册信息，默认为true，单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
      defaultZone: http://localhost:7001/eureka

config:
  info: 4
